FlattenLSTM:
  lr: 0.001
  epochs: 100
  input_size: 17954
  hidden_size: 1024
  num_layers: 2
  lstm_dropout: 0.2
  linear_features: [512, 256, 128, 232]
  linear_dropout: [0.4, 0.4, 0.4]
  last_layer_activation: Softmax(dim=1)

FlattenLSTM-1:
  lr: 0.0001
  epochs: 100
  input_size: 17954
  hidden_size: 1024
  num_layers: 2
  lstm_dropout: 0.2
  linear_features: [512, 256, 128, 232]
  linear_dropout: [0.4, 0.4, 0.4]
  last_layer_activation: Softmax(dim=1)

FlattenLSTM-2:
  lr: 0.001
  epochs: 100
  input_size: 17954
  hidden_size: 1024
  num_layers: 2
  lstm_dropout: 0.0
  linear_features: [512, 256, 128, 232]
  linear_dropout: [0.2, 0.2, 0.2]
  last_layer_activation: Softmax(dim=1)

FlattenLSTM-3:
  lr: 0.001
  epochs: 100
  input_size: 17954
  hidden_size: 512
  num_layers: 4
  lstm_dropout: 0.2
  linear_features: [512, 256, 128, 232]
  linear_dropout: [0.4, 0.4, 0.4]
  last_layer_activation: Softmax(dim=1)

FlattenLSTM-1-1:
  lr: 0.0001
  epochs: 100
  input_size: 17954
  hidden_size: 1024
  num_layers: 2
  lstm_dropout: 0.4
  linear_features: [512, 256, 128, 232]
  linear_dropout: [0.5, 0.5, 0.5]
  last_layer_activation: Softmax(dim=1)

FlattenLSTM-1-2:
  lr: 0.0001
  epochs: 100
  input_size: 17954
  hidden_size: 2048
  num_layers: 2
  lstm_dropout: 0.2
  linear_features: [512, 256, 128, 232]
  linear_dropout: [0.4, 0.4, 0.4]
  last_layer_activation: Softmax(dim=1)

FlattenLSTM-2-1:
  lr: 0.001
  epochs: 100
  input_size: 17954
  hidden_size: 1024
  num_layers: 2
  lstm_dropout: 0.0
  linear_features: [512, 256, 128, 232]
  linear_dropout: [0.4, 0.4, 0.4]
  last_layer_activation: Softmax(dim=1)

FlattenLSTM-2-2:
  lr: 0.001
  epochs: 100
  input_size: 17954
  hidden_size: 2048
  num_layers: 2
  lstm_dropout: 0.0
  linear_features: [512, 256, 128, 232]
  linear_dropout: [0.2, 0.2, 0.2]
  last_layer_activation: Softmax(dim=1)
