net_organization:
  phylum:
    class_Arthropoda:
      - family_Arachnida
      - family_Insecta
    class_Chordata:
      - family_Actinopterygii
      - family_Amphibia
      - family_Aves
      - family_Mammalia
      - family_Reptilia

node_params:
  phylum:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: []
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/phylum.jpg
    pth_file: ./networks/hierarchical/phylum.pth

  class_Arthropoda:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Arthropoda]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/class_Arthropoda.jpg
    pth_file: ./networks/hierarchical/class_Arthropoda.pth

  family_Arachnida:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Arthropoda, Arachnida]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Arachnida.jpg
    pth_file: ./networks/hierarchical/family_Arachnida.pth

  family_Insecta:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Arthropoda, Insecta]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Insecta.jpg
    pth_file: ./networks/hierarchical/family_Insecta.pth

  class_Chordata:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Chordata]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/class_Chordata.jpg
    pth_file: ./networks/hierarchical/class_Chordata.pth

  family_Actinopterygii:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Chordata, Actinopterygii]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Actinopterygii.jpg
    pth_file: ./networks/hierarchical/family_Actinopterygii.pth

  family_Amphibia:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Chordata, Amphibia]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Amphibia.jpg
    pth_file: ./networks/hierarchical/family_Amphibia.pth

  family_Aves:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Chordata, Aves]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Aves.jpg
    pth_file: ./networks/hierarchical/family_Aves.pth

  family_Mammalia:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Chordata, Mammalia]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Mammalia.jpg
    pth_file: ./networks/hierarchical/family_Mammalia.pth

  family_Reptilia:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Chordata, Reptilia]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Reptilia.jpg
    pth_file: ./networks/hierarchical/family_Reptilia.pth



net_architecture:
  phylum:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 2]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  class_Arthropoda:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 2]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Arachnida:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 1]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Insecta:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 14]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  class_Chordata:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 5]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Actinopterygii:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 1]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Amphibia:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 11]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Aves:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 150]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Mammalia:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 53]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Reptilia:
    input_size: 17954
    hidden_size: 1024
    num_layers: 2
    lstm_dropout: 0.2
    linear_features: [64, 2]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()
