net_organization:
  phylum:
    class_Arthropoda:
      - family_Arachnida
      - family_Insecta
    class_Chordata:
      - family_Actinopterygii
      - family_Amphibia
      - family_Aves
      - family_Mammalia
      - family_Reptilia

node_params:
  phylum:
    type: CNN
    epochs: 10
    lr: 0.001
    order: []
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/phylum.jpg
    pth_file: ./networks/hierarchical/phylum.pth

  class_Arthropoda:
    type: CNN
    epochs: 10
    lr: 0.001
    order: [Arthropoda]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/class_Arthropoda.jpg
    pth_file: ./networks/hierarchical/class_Arthropoda.pth

  family_Arachnida:
    type: CNN
    epochs: 10
    lr: 0.001
    order: [Arthropoda, Arachnida]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Arachnida.jpg
    pth_file: ./networks/hierarchical/family_Arachnida.pth

  family_Insecta:
    type: LSTM
    epochs: 15
    lr: 0.003
    order: [Arthropoda, Insecta]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Insecta.jpg
    pth_file: ./networks/hierarchical/family_Insecta.pth

  class_Chordata:
    type: LSTM
    epochs: 15
    lr: 0.001
    order: [Chordata]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/class_Chordata.jpg
    pth_file: ./networks/hierarchical/class_Chordata.pth

  family_Actinopterygii:
    type: CNN
    epochs: 2
    lr: 0.001
    order: [Chordata, Actinopterygii]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Actinopterygii.jpg
    pth_file: ./networks/hierarchical/family_Actinopterygii.pth

  family_Amphibia:
    type: CNN
    epochs: 15
    lr: 0.001
    order: [Chordata, Amphibia]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Amphibia.jpg
    pth_file: ./networks/hierarchical/family_Amphibia.pth

  family_Aves:
    type: CNN
    epochs: 25
    lr: 0.001
    order: [Chordata, Aves]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Aves.jpg
    pth_file: ./networks/hierarchical/family_Aves.pth

  family_Mammalia:
    type: CNN
    epochs: 15
    lr: 0.001
    order: [Chordata, Mammalia]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Mammalia.jpg
    pth_file: ./networks/hierarchical/family_Mammalia.pth

  family_Reptilia:
    type: CNN
    epochs: 15
    lr: 0.0001
    order: [Chordata, Reptilia]
    log_file: ./logs/hierarchical/test_train.log
    img_file: ./images/hierarchical/family_Reptilia.jpg
    pth_file: ./networks/hierarchical/family_Reptilia.pth



net_architecture:
  phylum:
    input_shape: [3, 1024, 256]
    conv_channels: [8, 16, 32, 64, 64, 128]
    conv_kernel_size: [2, 2, 2, 2, 2, 2]
    pooling_size: [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]
    conv_dropout: [0.0, 0.0, 0.2, 0.2, 0.0, 0.0]
    linear_features: [64, 2]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  class_Arthropoda:
    input_shape: [3, 1024, 256]
    conv_channels: [8, 16, 32, 64, 64, 128]
    conv_kernel_size: [2, 2, 2, 2, 2, 2]
    pooling_size: [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]
    conv_dropout: [0.0, 0.0, 0.2, 0.2, 0.0, 0.0]
    linear_features: [64, 2]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Arachnida:
    input_shape: [3, 1024, 256]
    conv_channels: [8, 16, 32, 64, 64, 128]
    conv_kernel_size: [2, 2, 2, 2, 2, 2]
    pooling_size: [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]
    conv_dropout: [0.0, 0.0, 0.2, 0.2, 0.0, 0.0]
    linear_features: [64, 1]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Insecta:
    input_size: 17954
    hidden_size: 1024
    num_layers: 3
    lstm_dropout: 0.2
    linear_features: [1024, 512, 14]
    linear_dropout: [0.4, 0.4]
    last_layer_activation: Sigmoid()

  class_Chordata:
    input_size: 17954
    hidden_size: 2048
    num_layers: 3
    lstm_dropout: 0.2
    linear_features: [2048, 1024, 5]
    linear_dropout: [0.4, 0.4]
    last_layer_activation: Sigmoid()

  family_Actinopterygii:
    input_shape: [3, 1024, 256]
    conv_channels: [8, 16, 32, 64, 64, 128]
    conv_kernel_size: [2, 2, 2, 2, 2, 2]
    pooling_size: [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]
    conv_dropout: [0.0, 0.0, 0.2, 0.2, 0.0, 0.0]
    linear_features: [64, 1]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Amphibia:
    input_shape: [3, 1024, 256]
    conv_channels: [16, 32, 64, 64, 128, 256, 512]
    conv_kernel_size: [2, 2, 2, 2, 2, 2, 2]
    pooling_size: [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]
    conv_dropout: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    linear_features: [1024, 512, 11]
    linear_dropout: [0.2, 0.2]
    last_layer_activation: Sigmoid()

  family_Aves:
    input_shape: [3, 1024, 256]
    conv_channels: [8, 16, 32, 64, 64, 128]
    conv_kernel_size: [2, 2, 2, 2, 2, 2]
    pooling_size: [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]
    conv_dropout: [0.0, 0.0, 0.2, 0.2, 0.0, 0.0]
    linear_features: [64, 150]
    linear_dropout: [0.4]
    last_layer_activation: Sigmoid()

  family_Mammalia:
    input_shape: [3, 1024, 256]
    conv_channels: [32, 64, 128, 256, 512, 1024]
    conv_kernel_size: [2, 2, 2, 2, 2, 2]
    pooling_size: [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]
    conv_dropout: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
    linear_features: [2048, 1024, 53]
    linear_dropout: [0.4, 0.4]
    last_layer_activation: Sigmoid()

  family_Reptilia:
    input_shape: [3, 1024, 256]
    conv_channels: [8, 16, 32, 64, 64, 128, 256]
    conv_kernel_size: [2, 2, 2, 2, 2, 2, 2]
    pooling_size: [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]
    conv_dropout: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
    linear_features: [1024, 512, 2]
    linear_dropout: [0.5, 0.5]
    last_layer_activation: Sigmoid()
